<a href="https://colab.research.google.com/github/Priyank0302/ML_Project/blob/main/notebooks/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Statistics-With-Python-TheCompleteGuide/main/clead_google_playstore_data")

In [ ]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4,20,6,2018

In [ ]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
10835,Sya9a Maroc - FR,FAMILY,4.5,38,53000.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1,25,7,2017
10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3600.0,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1,6,7,2018
10837,Parkinson Exercices FR,MEDICAL,NaN,3,9500.0,1000,Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2,20,1,2017
10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,NaN,19,1,2015
10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19000.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,NaN,25,7,2018

In [ ]:
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,year
9610,Instabridge - Free WiFi Passwords and Hotspots,TOOLS,4.4,211308,NaN,10000000,Free,0.00,Everyone,Tools,2018-08-02,Varies with device,4.1,2,8,2018
5726,AV High School District,FAMILY,3.5,91,25000.0,10000,Free,0.00,Everyone,Education,2018-04-05,5.2.002,4.1,5,4,2018
465,imo free video calls and chat,COMMUNICATION,4.3,4785988,11000.0,500000000,Free,0.00,Everyone,Communication,2018-06-08,9.8.000000010501,4.0,8,6,2018
853,Toca Life: City,EDUCATION,4.7,31085,24000.0,500000,Paid,3.99,Everyone,Education;Pretend Play,2018-07-06,1.5-play,4.4,6,7,2018
5272,How it works: AK-74N,FAMILY,4.4,1031,48000.0,100000,Free,0.00,Everyone,Entertainment,2018-01-09,2.1.9f0,4.0.3,9,1,2018
7310,Bhunaksha CG,TOOLS,4.1,67,4100.0,10000,Free,0.00,Everyone,Tools,2018-05-07,1.0.0,4.1,7,5,2018
1364,Geocaching®,HEALTH_AND_FITNESS,4.1,62616,NaN,5000000,Free,0.00,Teen,Health & Fitness,2018-08-02,Varies with device,NaN,2,8,2018
8914,DU Collage Maker - Photo Collage & Grid & Layout,PHOTOGRAPHY,4.7,4595,2500.0,100000,Free,0.00,Everyone,Photography,2017-09-04,1.4.0,4.0,4,9,2017
3449,Lavender Emoji Keyboard Theme,PERSONALIZATION,4.1,12008,6100.0,1000000,Free,0.00,Everyone,Personalization,2016-05-27,5.0,4.0,27,5,2016
196,Job Search by ZipRecruiter,BUSINESS,4.8,148945,25000.0,1000000,Free,0.00,Everyone,Business,2018-07-19,5.2.8,5.0,19,7,2018

In [ ]:
df.shape

(10840, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     9476 non-null   object
 13  day             10840 non-null  int64
 14  month           10840 non-null  int64
 15  year            10840 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.3+ MB